<template>
  <div class="portfolio-page semester-page">
    <header><div><p class="eyebrow">让这一学期有节奏</p><h1>学期模式</h1><p>按课程安排每周任务与考试，进度由你确认。</p></div><button type="button" :disabled="busy" @click="load">刷新学期</button></header>
    <p v-if="loading" role="status">正在读取课程与进度…</p><DataState v-else-if="loadError" :error="loadError" @retry="load" />
    <template v-else>
      <p v-if="actionError" role="alert">{{ actionError }}</p>
      <section v-if="state" class="portfolio-panel semester-overview"><div class="section-head"><div><h2>{{ state.config.title }}</h2><p>{{ state.config.start_date }} 至 {{ state.config.end_date }} · {{ state.config.courses.length }} 门课程 · {{ completed }}/{{ state.tasks.length }} 项完成</p></div><button type="button" :disabled="busy" @click="edit">调整课程编排</button></div><p>每周预计 {{ weeklyMinutes }} 分钟。完成任务记录代表自报进度，不等于掌握度或考试成绩。</p><div class="course-links"><span v-for="course in state.config.courses" :key="course.course_id"><b>{{ course.title }}</b><RouterLink v-if="course.source_id" :to="{ path: '/knowledge', query: { source: course.source_id } }">查看课程资料</RouterLink></span></div></section>
      <form v-if="editing || !state" class="portfolio-panel" @submit.prevent="arrange">
        <h2>{{ state ? '调整学期' : '建立本学期' }}</h2><div class="field-grid"><label>学期名称<input v-model="draft.title" required maxlength="120"></label><label>开始日期<input v-model="draft.start_date" type="date" required></label><label>结束日期<input v-model="draft.end_date" type="date" required :min="draft.start_date"></label></div>
        <fieldset v-for="(course, index) in draft.courses" :key="course.course_id"><legend>课程 {{ index + 1 }}</legend><div class="field-grid"><label>课程名称<input v-model="course.title" required maxlength="120"></label><label>每周投入分钟<input v-model.number="course.weekly_minutes" type="number" min="10" max="600" step="1" required></label><label>每周任务日<select v-model.number="course.weekday"><option v-for="(day, weekday) in weekdays" :key="day" :value="weekday">{{ day }}</option></select></label><label>考试日期（可选）<input :value="course.exam_date || ''" type="date" :min="draft.start_date" :max="draft.end_date" @input="course.exam_date = ($event.target as HTMLInputElement).value || null"></label></div><label>每周学习目标<textarea v-model="course.objective" rows="2" required maxlength="1000" placeholder="填写每周要实际完成的课程任务"></textarea></label><label>关联已有资料（可选）<select v-model="course.source_id"><option :value="null">暂不关联</option><option v-for="source in sources" :key="source.source_id" :value="source.source_id">{{ source.original_name }}</option><option v-if="course.source_id && !sources.some(s => s.source_id === course.source_id)" :value="course.source_id">已保存的资料关联（确认时校验）</option></select></label><button type="button" :disabled="draft.courses.length === 1" @click="draft.courses.splice(index, 1)">移除课程</button></fieldset>
        <p v-if="sourcesError" role="status">{{ sourcesError }}。可不关联资料继续编排。</p><div class="actions"><button type="button" :disabled="draft.courses.length >= 20" @click="addCourse">添加课程</button><button type="submit" class="primary" :disabled="busy">预览学期编排</button><button v-if="state" type="button" @click="editing = false">取消调整</button></div>
      </form>
      <section v-if="state" class="portfolio-panel semester-tasks"><div class="section-head"><h2>课程任务</h2><div class="actions"><label>周次<select v-model="week" aria-label="周次" @change="page = 0"><option :value="0">全部周次</option><option v-for="value in weeks" :key="value" :value="value">第{{ value }}周</option></select></label><label class="consent"><input v-model="pendingOnly" type="checkbox" @change="page = 0">仅看未完成</label></div></div><p>共 {{ filtered.length }} 项，每页30项。截止日期按你指定的学期和每周任务日安排。</p><ul class="semester-task-list"><li v-for="task in visible" :key="task.task_id"><label class="consent"><input type="checkbox" :checked="task.completed" :disabled="busy" :aria-label="`${courseNames.get(task.course_id)} 第${task.week}周 ${task.kind === 'exam' ? '考试' : '任务'}完成`" @change="toggle(task.task_id, !task.completed)"><span><b>{{ task.title }}</b><small>{{ courseNames.get(task.course_id) }} · 第{{ task.week }}周 · {{ task.due_date }}{{ task.minutes ? ` · ${task.minutes}分钟` : '' }}{{ task.completed ? ' · 已完成' : '' }}</small></span></label></li></ul><p v-if="!filtered.length">这个范围内暂无任务。</p><div class="actions"><button type="button" :disabled="!page" @click="page--">上一页</button><span>第{{ page + 1 }}/{{ Math.max(1, Math.ceil(filtered.length / 30)) }}页</span><button type="button" :disabled="(page + 1) * 30 >= filtered.length" @click="page++">下一页</button></div></section>
    </template>
  </div>
</template>
<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { ElMessageBox } from 'element-plus'
import DataState from '../components/DataState.vue'
import { confirmSemester, getKnowledgeSources, getSemester, previewSemester, updateSemesterTask } from '../services/api'
import type { SemesterConfig, SemesterState } from '../types/portfolio'
const state = ref<SemesterState | null>(null), loading = ref(true), busy = ref(false), editing = ref(false), loadError = ref(''), actionError = ref(''), sourcesError = ref('')
const sources = ref<{ source_id: string; original_name: string }[]>([]), week = ref(0), pendingOnly = ref(false), page = ref(0)
const draft = ref<SemesterConfig>({ schema_version: 1, revision: 0, title: '', start_date: '', end_date: '', courses: [] })
const weekdays = ['星期一', '星期二', '星期三', '星期四', '星期五', '星期六', '星期日']
const completed = computed(() => state.value?.tasks.filter(task => task.completed).length || 0)
const weeklyMinutes = computed(() => state.value?.config.courses.reduce((sum, course) => sum + course.weekly_minutes, 0) || 0)
const courseNames = computed(() => new Map(state.value?.config.courses.map(course => [course.course_id, course.title])))
const weeks = computed(() => Math.max(0, ...state.value?.tasks.map(task => task.week) || []))
const filtered = computed(() => state.value?.tasks.filter(task => (!week.value || task.week === week.value) && (!pendingOnly.value || !task.completed)) || [])
const visible = computed(() => filtered.value.slice(page.value * 30, (page.value + 1) * 30))
function addCourse() { draft.value.courses.push({ course_id: crypto.randomUUID(), title: '', objective: '', weekly_minutes: 90, weekday: 6, source_id: null, exam_date: null }) }
function edit() { if (state.value) draft.value = JSON.parse(JSON.stringify(state.value.config)); editing.value = true }
async function load() { loading.value = true; loadError.value = ''; try { state.value = await getSemester(); if (!state.value && !draft.value.courses.length) addCourse() } catch (e: any) { loadError.value = e.message } finally { loading.value = false }; try { sources.value = await getKnowledgeSources() } catch (e: any) { sourcesError.value = e.message } }
async function arrange() { busy.value = true; actionError.value = ''; try { const config = JSON.parse(JSON.stringify(draft.value)) as SemesterConfig; const preview = await previewSemester(config); try { await ElMessageBox.confirm(`将安排${preview.week_count}周、${preview.task_count}项任务，每周预计${preview.weekly_minutes}分钟。原有${preview.previous_completed}项完成记录保留为历史版本。${preview.notice}`, '确认学期编排', { confirmButtonText: '确认编排', cancelButtonText: '取消' }) } catch { return }; await confirmSemester(config, preview.confirmation_token); state.value = await getSemester(); editing.value = false; page.value = 0; week.value = 0 } catch (e: any) { actionError.value = e.message || '编排失败，原学期保留' } finally { busy.value = false } }
async function toggle(id: string, completed: boolean) { if (!state.value) return; busy.value = true; actionError.value = ''; try { state.value = await updateSemesterTask(id, state.value.config.revision, completed); page.value = Math.min(page.value, Math.max(0, Math.ceil(filtered.value.length / 30) - 1)) } catch (e: any) { actionError.value = e.message || '更新失败，原进度保留' } finally { busy.value = false } }
onMounted(load)
</script>
<style src="../styles/portfolio.css"></style>
<style scoped>.semester-overview,.semester-tasks{margin-bottom:24px;margin-top:24px}.course-links{display:flex;gap:16px;flex-wrap:wrap}.course-links span{display:flex;flex-direction:column;gap:8px}.semester-task-list{list-style:none;padding:0}.semester-task-list li{padding:12px 0;border-top:1px solid var(--border-color)}.semester-task-list small{display:block;color:var(--text-secondary);line-height:1.8}.semester-task-list b{overflow-wrap:anywhere}.semester-tasks .actions{align-items:center}.semester-tasks label{margin:0}</style>
